// <auto-generated />
using System;
using Inscripciones.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inscripciones.Migrations
{
    [DbContext(typeof(InscripcionesContext))]
    [Migration("20240608155119_AgregandoDatosSemilladeAlumno,Carrera,anioCarreraYMateria")]
    partial class AgregandoDatosSemilladeAlumnoCarreraanioCarreraYMateria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Inscripciones.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoNombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("alumnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApellidoNombre = "Bustamante Federico Valentin",
                            Direccion = "Belgrano 123",
                            Email = "Federico@gmail.com",
                            Telefono = "3498675354"
                        },
                        new
                        {
                            Id = 2,
                            ApellidoNombre = "Javier López",
                            Direccion = "Calle de la Vida 101",
                            Email = "javier.lopez@example.com",
                            Telefono = "3498765445"
                        },
                        new
                        {
                            Id = 3,
                            ApellidoNombre = "Ana María Gómez",
                            Direccion = "Calle Falsa 123",
                            Email = "anamaria@gmail.com",
                            Telefono = "3498765432"
                        },
                        new
                        {
                            Id = 4,
                            ApellidoNombre = "Carlos Alberto Pérez",
                            Direccion = "Av Siempre Viva 742",
                            Email = "carlos.perez@example.com",
                            Telefono = "3498765433"
                        },
                        new
                        {
                            Id = 5,
                            ApellidoNombre = "Laura González",
                            Direccion = "Bv. Belgrano 154",
                            Email = "laura.gonzalez@example.com",
                            Telefono = "3498765434"
                        },
                        new
                        {
                            Id = 6,
                            ApellidoNombre = "Marcelo Diaz",
                            Direccion = "Calle de la Amargura 7",
                            Email = "marcelo.diaz@example.com",
                            Telefono = "3498765435"
                        },
                        new
                        {
                            Id = 7,
                            ApellidoNombre = "Verónica Herrera",
                            Direccion = "Calle de los Enamorados 15",
                            Email = "veronica.herrera@example.com",
                            Telefono = "3498765436"
                        },
                        new
                        {
                            Id = 8,
                            ApellidoNombre = "Miguel Angel Rodríguez",
                            Direccion = "Av. de Mayo 123",
                            Email = "miguel.rodriguez@example.com",
                            Telefono = "3498765437"
                        },
                        new
                        {
                            Id = 9,
                            ApellidoNombre = "Paula Fernández",
                            Direccion = "Calle de los Pinos 24",
                            Email = "paula.fernandez@example.com",
                            Telefono = "3498765438"
                        },
                        new
                        {
                            Id = 10,
                            ApellidoNombre = "Gabriel Suárez",
                            Direccion = "Calle Falsa 345",
                            Email = "gabriel.suarez@example.com",
                            Telefono = "3498765439"
                        });
                });

            modelBuilder.Entity("Inscripciones.Models.AnioCarrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.ToTable("aniocarreras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarreraId = 1,
                            Nombre = "1er año"
                        },
                        new
                        {
                            Id = 2,
                            CarreraId = 1,
                            Nombre = "2do año"
                        },
                        new
                        {
                            Id = 3,
                            CarreraId = 1,
                            Nombre = "3er año"
                        },
                        new
                        {
                            Id = 4,
                            CarreraId = 2,
                            Nombre = "1er año"
                        },
                        new
                        {
                            Id = 5,
                            CarreraId = 2,
                            Nombre = "2do año"
                        },
                        new
                        {
                            Id = 6,
                            CarreraId = 2,
                            Nombre = "3er año"
                        },
                        new
                        {
                            Id = 7,
                            CarreraId = 3,
                            Nombre = "1er año"
                        },
                        new
                        {
                            Id = 8,
                            CarreraId = 3,
                            Nombre = "2do año"
                        },
                        new
                        {
                            Id = 9,
                            CarreraId = 3,
                            Nombre = "3er año"
                        },
                        new
                        {
                            Id = 10,
                            CarreraId = 4,
                            Nombre = "1er año"
                        },
                        new
                        {
                            Id = 11,
                            CarreraId = 4,
                            Nombre = "2do año"
                        },
                        new
                        {
                            Id = 12,
                            CarreraId = 4,
                            Nombre = "3er año"
                        },
                        new
                        {
                            Id = 13,
                            CarreraId = 5,
                            Nombre = "1er año"
                        },
                        new
                        {
                            Id = 14,
                            CarreraId = 5,
                            Nombre = "2do año"
                        },
                        new
                        {
                            Id = 15,
                            CarreraId = 5,
                            Nombre = "3er año"
                        },
                        new
                        {
                            Id = 16,
                            CarreraId = 5,
                            Nombre = "4to año"
                        },
                        new
                        {
                            Id = 17,
                            CarreraId = 6,
                            Nombre = "1er año"
                        },
                        new
                        {
                            Id = 18,
                            CarreraId = 6,
                            Nombre = "2do año"
                        },
                        new
                        {
                            Id = 19,
                            CarreraId = 6,
                            Nombre = "3er año"
                        },
                        new
                        {
                            Id = 20,
                            CarreraId = 6,
                            Nombre = "4to año"
                        },
                        new
                        {
                            Id = 21,
                            CarreraId = 7,
                            Nombre = "1er año"
                        },
                        new
                        {
                            Id = 22,
                            CarreraId = 7,
                            Nombre = "2do año"
                        },
                        new
                        {
                            Id = 23,
                            CarreraId = 7,
                            Nombre = "3er año"
                        },
                        new
                        {
                            Id = 24,
                            CarreraId = 7,
                            Nombre = "4to año"
                        },
                        new
                        {
                            Id = 25,
                            CarreraId = 8,
                            Nombre = "1er año"
                        },
                        new
                        {
                            Id = 26,
                            CarreraId = 8,
                            Nombre = "2do año"
                        },
                        new
                        {
                            Id = 27,
                            CarreraId = 8,
                            Nombre = "3er año"
                        },
                        new
                        {
                            Id = 28,
                            CarreraId = 8,
                            Nombre = "4to año"
                        });
                });

            modelBuilder.Entity("Inscripciones.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("carreras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tecnicatura Superior en Desarrollo de Software"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Tecnicatura Superior en Soporte de Infraestructura"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Tecnicatura Superior en Gestion de las Organizaciones"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Tecnicatura Superior en Enfermeria"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Profesorado de Educación Secundaria en Ciencias de la Administración"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Profesorado de Educación Inicial"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Profesorado de Educación Secundaria en Economía"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Profesorado de Educación Tecnológica"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Licenciatura en Cooperativismo y Mutualismo"
                        });
                });

            modelBuilder.Entity("Inscripciones.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("CarreraId");

                    b.ToTable("inscripcion");
                });

            modelBuilder.Entity("Inscripciones.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioCarreraId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AnioCarreraId");

                    b.ToTable("materia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnioCarreraId = 25,
                            Nombre = "Pedagogía"
                        },
                        new
                        {
                            Id = 2,
                            AnioCarreraId = 25,
                            Nombre = "Movimiento y Cuerpo"
                        },
                        new
                        {
                            Id = 3,
                            AnioCarreraId = 25,
                            Nombre = "Práctica Docente I: Escenarios Educativos"
                        },
                        new
                        {
                            Id = 4,
                            AnioCarreraId = 25,
                            Nombre = "Introducción a la Tecnología"
                        },
                        new
                        {
                            Id = 5,
                            AnioCarreraId = 25,
                            Nombre = "Historia de la Tecnología"
                        },
                        new
                        {
                            Id = 6,
                            AnioCarreraId = 25,
                            Nombre = "Diseño y Producción de la Técnología 1"
                        },
                        new
                        {
                            Id = 7,
                            AnioCarreraId = 25,
                            Nombre = "Matemática"
                        },
                        new
                        {
                            Id = 8,
                            AnioCarreraId = 25,
                            Nombre = "Física"
                        },
                        new
                        {
                            Id = 9,
                            AnioCarreraId = 26,
                            Nombre = "Psicología de la Educación"
                        },
                        new
                        {
                            Id = 10,
                            AnioCarreraId = 26,
                            Nombre = "Didáctica y Curriculum"
                        },
                        new
                        {
                            Id = 11,
                            AnioCarreraId = 26,
                            Nombre = "Instituciones Educativas"
                        },
                        new
                        {
                            Id = 12,
                            AnioCarreraId = 26,
                            Nombre = "Práctica Docente II: La Institución Escolar"
                        },
                        new
                        {
                            Id = 13,
                            AnioCarreraId = 26,
                            Nombre = "Sujetos de la Educación I"
                        },
                        new
                        {
                            Id = 14,
                            AnioCarreraId = 26,
                            Nombre = "Tic para la Enseñanza"
                        },
                        new
                        {
                            Id = 15,
                            AnioCarreraId = 26,
                            Nombre = "Procesos Productivos"
                        },
                        new
                        {
                            Id = 16,
                            AnioCarreraId = 26,
                            Nombre = "Tecnológica II"
                        },
                        new
                        {
                            Id = 17,
                            AnioCarreraId = 26,
                            Nombre = "Didáctica Específica I"
                        },
                        new
                        {
                            Id = 18,
                            AnioCarreraId = 27,
                            Nombre = "Filosofía y Educación"
                        },
                        new
                        {
                            Id = 19,
                            AnioCarreraId = 27,
                            Nombre = "Historia Social de la Educación"
                        },
                        new
                        {
                            Id = 20,
                            AnioCarreraId = 27,
                            Nombre = "Metodología de la Investigación"
                        },
                        new
                        {
                            Id = 21,
                            AnioCarreraId = 27,
                            Nombre = "Práctica Docente III: La Clase"
                        },
                        new
                        {
                            Id = 22,
                            AnioCarreraId = 27,
                            Nombre = "Sujetos de la Educación II"
                        },
                        new
                        {
                            Id = 23,
                            AnioCarreraId = 27,
                            Nombre = "Materiales"
                        },
                        new
                        {
                            Id = 24,
                            AnioCarreraId = 27,
                            Nombre = "Química"
                        },
                        new
                        {
                            Id = 25,
                            AnioCarreraId = 27,
                            Nombre = "Procesos de Control"
                        },
                        new
                        {
                            Id = 26,
                            AnioCarreraId = 27,
                            Nombre = "Tecnologías Regionales"
                        },
                        new
                        {
                            Id = 27,
                            AnioCarreraId = 27,
                            Nombre = "Diseño y Producción Tecnológica III"
                        },
                        new
                        {
                            Id = 28,
                            AnioCarreraId = 27,
                            Nombre = "Didáctica Específica II"
                        },
                        new
                        {
                            Id = 29,
                            AnioCarreraId = 28,
                            Nombre = "Ética y Trabajo Docente"
                        },
                        new
                        {
                            Id = 30,
                            AnioCarreraId = 28,
                            Nombre = "Educación Sexual Integral"
                        },
                        new
                        {
                            Id = 31,
                            AnioCarreraId = 28,
                            Nombre = "Unidades de Definición Institucional I"
                        },
                        new
                        {
                            Id = 32,
                            AnioCarreraId = 28,
                            Nombre = "Unidades de Definición Institucional II"
                        },
                        new
                        {
                            Id = 33,
                            AnioCarreraId = 28,
                            Nombre = "Prácticas de Investigación"
                        },
                        new
                        {
                            Id = 34,
                            AnioCarreraId = 28,
                            Nombre = "Práctica Docente IV: El Rol Docente y su Práctica"
                        },
                        new
                        {
                            Id = 35,
                            AnioCarreraId = 28,
                            Nombre = "Biotecnología"
                        },
                        new
                        {
                            Id = 36,
                            AnioCarreraId = 28,
                            Nombre = "Procesos de Comunicación"
                        },
                        new
                        {
                            Id = 37,
                            AnioCarreraId = 28,
                            Nombre = "Problemáticas Sociotécnicas"
                        },
                        new
                        {
                            Id = 38,
                            AnioCarreraId = 28,
                            Nombre = "Diseño y Producción Tecnológica IV"
                        },
                        new
                        {
                            Id = 39,
                            AnioCarreraId = 28,
                            Nombre = "Taller de Producción Didáctica"
                        });
                });

            modelBuilder.Entity("Inscripciones.Models.AnioCarrera", b =>
                {
                    b.HasOne("Inscripciones.Models.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("Inscripciones.Models.Inscripcion", b =>
                {
                    b.HasOne("Inscripciones.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inscripciones.Models.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("Inscripciones.Models.Materia", b =>
                {
                    b.HasOne("Inscripciones.Models.AnioCarrera", "AnioCarrera")
                        .WithMany()
                        .HasForeignKey("AnioCarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnioCarrera");
                });
#pragma warning restore 612, 618
        }
    }
}
